### ISSUE TITLE
Should prime() wrap instance association functions?

### ISSUE THREAD

**Issue by HriBB** [mattecapu/dataloader-sequelize-wrapper#2]
How can we wrap association functions for manually loaded instances?

For example, what if I do this?

```
async location(_, { slug }, { cache }) {
  const location = await db.Location.find({ where: { slug } })
  cache.from('Location').prime(location)
  return location
},
```

Location instance will be cached, but it's association functions wont be wrapped, so when I do this later

```
async children(location, { cache }) {
  return location.getChildren()
},
```

I am actually calling the original getter.

The way I see it, there are several ways to fix this problem.

1. `prime()` function could check if instance is wrapped and if not, wrap and return it
2. expose `wrapAssociationsCalls` function so users can do it manually
3. expose `find[One|All]` methods on `PeekingDataLoader` that load and cache data and return all instances wrapped

What do you think?

**Comment by mattecapu** [comment]
Mmh this looks legitimate. I think the best option is to expose the wrapper function, so to give more flexibility to the user. 
This poses some questions however, because originally, I pictured to use the library only with full (= all the attributes are fetched) objects. Priming with partial object could silently corrupt the cache and produce undefined behavior.
I thought of making the caching more granular (attribute-level), but as of now I don't need it in the project I created this for,  so I didn't implement it yet.

Meanwhile I think exposing the function and warn the user in the README should be enough. Like for the other issue, feel free to submit a PR or I will do it by myself in the days coming.
